theme: jekyll-theme-hacker
plugins:
- jekyll-seo-tag

# SEO stuff starts here.
title: AAAAXY
tagline: A nonlinear puzzle platformer taking place in non-Euclidean geometry.
description: >-
  AAAAXY is a nonlinear puzzle platformer taking place in non-Euclidean
  geometry.

  Although your general goal is reaching the surprising end of the game,
  you are encouraged to set your own goals while playing. Exploration will
  be rewarded, and secrets await you\!

  So jump and run around, and enjoy losing your sense of orientation in
  this World of Wicked Weirdness. Find out what Van Vlijmen will make you
  do. Pick a path, get inside a Klein Bottle, recognize some memes, and by
  all means: don't look up.
url: https://divVerent.github.io
logo: /logo.png
author:
  name: Rudolf Polzer
  url: https://github.com/divVerent
social:
  name: Rudolf "divVerent" Polzer
  links:
    - https://github.com/divVerent
    - https://misskey.de/@divVerent
    - https://divVerent.itch.io
    - https://gamejolt.com/@divVerent
google_site_verification: HfskWtLbuwMdqYTilJPGRLxQ7AVZoAeUa5cnwwRD6iw
locale: en_US
