remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

# SEO stuff starts here.
title: AAAAXY
url: https://divVerent.github.io
logo: /logo.png
author:
  name: Rudolf Polzer
  url: https://github.com/divVerent
social:
  name: Rudolf "divVerent" Polzer
  links:
    - https://github.com/divVerent
    - https://misskey.de/@divVerent
    - https://divVerent.itch.io
google_site_verification: HfskWtLbuwMdqYTilJPGRLxQ7AVZoAeUa5cnwwRD6iw
locale: en_US
